[package]
name = "bitwarden_rs"
version = "1.0.0"
authors = ["Daniel García <dani-garcia@users.noreply.github.com>"]
edition = "2018"

repository = "https://github.com/dani-garcia/bitwarden_rs"
readme = "README.md"
license = "GPL-3.0-only"
publish = false
build = "build.rs"

[features]
enable_syslog = ["syslog", "fern/syslog-4"]

[dependencies]
# Web framework for nightly with a focus on ease-of-use, expressibility, and speed.
rocket = { version = "0.4.0", features = ["tls"], default-features = false }
rocket_contrib = "0.4.0"

# HTTP client
reqwest = "0.9.11"

# multipart/form-data support
multipart = "0.16.1"

# WebSockets library
ws = "0.8.0"

# MessagePack library
rmpv = "0.4.0"

# Concurrent hashmap implementation
chashmap = "2.2.2"

# A generic serialization/deserialization framework
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

# Logging
log = "0.4.6"
fern = "0.5.7"
syslog = { version = "4.0.1", optional = true }

# A safe, extensible ORM and Query builder
diesel = { version = "1.4.1", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = { version = "1.4.0", features = ["sqlite"] }

# Bundled SQLite
libsqlite3-sys = { version = "0.12.0", features = ["bundled"] }

# Crypto library
ring = "0.14.6"

# UUID generation
uuid = { version = "0.7.2", features = ["v4"] }

# Date and time library for Rust
chrono = "0.4.6"

# TOTP library
oath = "0.10.2"

# Data encoding library
data-encoding = "2.1.2"

# JWT library
jsonwebtoken = "6.0.0"

# U2F library
u2f = "0.1.5"

# Yubico Library
yubico = { version = "0.5.1", features = ["online"], default-features = false }

# A `dotenv` implementation for Rust
dotenv = { version = "0.13.0", default-features = false }

# Lazy static macro
lazy_static = "1.3.0"

# More derives
derive_more = "0.14.0"

# Numerical libraries
num-traits = "0.2.6"
num-derive = "0.2.4"

# Email libraries
lettre = "0.9.0"
lettre_email = "0.9.0"
native-tls = "0.2.2"

# Template library
handlebars = "1.1.0"

# For favicon extraction from main website
soup = "0.3.0"
regex = "1.1.2"

[patch.crates-io]
# Add support for Timestamp type
rmp = { git = 'https://github.com/dani-garcia/msgpack-rust' }

# Update to ring 0.14
rocket = { git = 'https://github.com/dani-garcia/Rocket', rev = 'a9c9ee3b776b1' }
rocket_contrib = { git = 'https://github.com/dani-garcia/Rocket', rev = 'a9c9ee3b776b1' }
hyper-sync-rustls = { git = 'https://github.com/dani-garcia/hyper-sync-rustls', rev = 'b81f5c42339b4' }
jsonwebtoken = { git = 'https://github.com/Keats/jsonwebtoken', rev = 'be27206088f0a' }

# Use new native_tls version 0.2
lettre = { git = 'https://github.com/lettre/lettre', rev = 'c988b1760ad81' }
lettre_email = { git = 'https://github.com/lettre/lettre', rev = 'c988b1760ad81' }
